# .github/workflows/build-job.yml
name: Build NixOS Configuration

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build-result.outputs.success }}

    steps:
      - name: Maximize build space
        uses: gmij/max-build-space@main
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-large-packages: "true"

      - name: Show available disk space
        run: df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@master
        with:
          name: avanderbergh
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ${{ inputs.host }}
        run: |
          echo "Building ${{ inputs.host }}..."
          if nix build .#nixosConfigurations.${{ inputs.host }}.config.system.build.toplevel --system x86_64-linux --accept-flake-config --show-trace --keep-going; then
            echo "success=true" >> $GITHUB_ENV
          else
            echo "Build failed, listing flake.lock for debugging:"
            cat flake.lock
            echo "success=false" >> $GITHUB_ENV  
          fi

      - name: Determine build result
        id: build-result
        run: echo "success=${{ env.success }}" >> $GITHUB_OUTPUT
