name: Build NixOS Configurations

on:
  push:
    branches:
      - main

jobs:
  build-farnsworth:
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build-result.outputs.success }}

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@master
        with:
          name: avanderbergh
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Farnsworth
        run: |
          echo "Building Hermes..."
          if nix build .#nixosConfigurations.farnsworth.config.system.build.toplevel --system x86_64-linux --accept-flake-config --show-trace --keep-going; then
            echo "success=true" >> $GITHUB_ENV
          else
            echo "Build failed, listing flake.lock for debugging:"
            cat flake.lock
            echo "success=false" >> $GITHUB_ENV  
          fi

      - name: Determine build result
        id: build-result
        run: echo "success=${{ env.success }}" >> $GITHUB_OUTPUT
