# .github/workflows/build.yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  build-farnsworth:
    uses: ./.github/workflows/build-job.yml
    with:
      host: farnsworth

  build-hermes:
    uses: ./.github/workflows/build-job.yml
    with:
      host: hermes

  build-zoidberg:
    uses: ./.github/workflows/build-job.yml
    with:
      host: zoidberg

  final-status:
    runs-on: ubuntu-latest
    needs: [build-farnsworth, build-hermes, build-zoidberg]
    steps:
      - name: Set final build status
        run: |
          if [[ "${{ needs.build-farnsworth.outputs.build-success }}" == "false" || "${{ needs.build-hermes.outputs.build-success }}" == "false" || "${{ needs.build-zoidberg.outputs.build-success }}" == "false" ]]; then
            echo "One or more builds failed."
            exit 1
          else
            echo "All builds succeeded."
