keys:
  # User
  - &avanderbergh 741EDA0A1F942978D0E612ED938036D74671D8D5
  # Hosts
  - &farnsworth age14sf3znxwz42nugrrqcf8ysnq6qukrq7llxnjs2gnfkh8yvaamv3qtfraqj
  - &hermes age1mhc2s9n6j7v8hafz7gpqen0c23nfr37kagv7dnsg0jn4l0753yuspc0y7j
  - &zoidberg age1dqp6pkrs86qmaxq3keggu94gfeg2qy0e9scurr5j7kgr53phs4ush7wd7u
creation_rules:
  - key_groups:
      # TODO: Add pgp key group
      # - pgp:
      #     - *avanderbergh
      - age:
          - *farnsworth
          - *hermes
          - *zoidberg
